#include <Arduino.h>

/******************************************************************************
 * File Name:   main.c
 *
 * Description: This is the source code for the XMC MCU: Empty Application
 *              Template for ModusToolbox.
 *
 * Related Document: See README.md
 *
 ******************************************************************************
 *
 * Copyright (c) 2015-2021, Infineon Technologies AG
 * All rights reserved.
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 *****************************************************************************/

#include <Arduino.h>

#define CCU4_Module_Number 0U
#define CCU4_Slice_Number 0U
#define CCU4_Module_Pointer CCU40
#define CCU4_SLICE_Pointer CCU40_CC40

XMC_GPIO_CONFIG_t Intr_pin = {.mode = XMC_GPIO_MODE_OUTPUT_PUSH_PULL,
                              .output_level = XMC_GPIO_OUTPUT_LEVEL_LOW,
                              .output_strength = XMC_GPIO_OUTPUT_STRENGTH_STRONG_SOFT_EDGE};

// Initialisierung (wie im Original)
XMC_CCU4_SLICE_COMPARE_CONFIG CCU4_Slice_Config = {
    // Bit field settings
    {
      {
    .timer_mode = XMC_CCU4_SLICE_TIMER_COUNT_MODE_EA,
    .monoshot = XMC_CCU4_SLICE_TIMER_REPEAT_MODE_REPEAT,
    .shadow_xfer_clear = 0U,
    .dither_timer_period = 0U,
    .dither_duty_cycle = 0U,
    .prescaler_mode = XMC_CCU4_SLICE_PRESCALER_MODE_NORMAL,
    .mcm_enable = 0U
    }
  },
    // Further settings
    .prescaler_initval = XMC_CCU4_SLICE_PRESCALER_16384,
    .float_limit = 0U,
    .dither_limit = 0U,
    .passive_level = XMC_CCU4_SLICE_OUTPUT_PASSIVE_LEVEL_LOW,
    .timer_concatenation = 0U
};

  XMC_GPIO_CONFIG_t tx_config = {
                                   .mode             = XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2,
                                   .output_level     = XMC_GPIO_OUTPUT_LEVEL_HIGH,
                                   .output_strength  = XMC_GPIO_OUTPUT_STRENGTH_STRONG_SOFT_EDGE
                                 };

  XMC_UART_CH_CONFIG_t uart_config = {
                                        .baudrate       = 9600,   // Default setting
                                        .data_bits      = 8,
                                        .frame_length   = 8,
                                        .stop_bits      = 1,
                                        .oversampling   = 16,
                                        .parity_mode    = XMC_USIC_CH_PARITY_MODE_NONE
                                      };

void uart_init(uint32_t baudrate) {

  uart_config.baudrate = baudrate;

  /*Initialize and configure UART0 on channel 0 */
  XMC_UART_CH_Init(XMC_UART0_CH0, &uart_config);

  /*Configure TX*/
  XMC_GPIO_Init(P1_5, &tx_config);

  /*Set input source path*/
  XMC_USIC_CH_SetInputSource(XMC_UART0_CH0, XMC_USIC_CH_INPUT_DX0, 1U);

  /*Configure transmit FIFO*/
  XMC_USIC_CH_TXFIFO_Configure(XMC_UART0_CH0, 16U, XMC_USIC_CH_FIFO_SIZE_16WORDS, 1U);

  /*Configure receive FIFO*/
  XMC_USIC_CH_RXFIFO_Configure(XMC_UART0_CH0, 0U, XMC_USIC_CH_FIFO_SIZE_16WORDS, 15U);

  /*Start UART */
  XMC_UART_CH_Start(XMC_UART0_CH0);
}

void uart_write(char message[]) {
  uint8_t idx;
  /*Transmit the string "Infineon" */
  while (message[idx] != 0)
    {
      XMC_UART_CH_Transmit(XMC_UART0_CH0,message[idx]);
      idx++;

      /*Wait for transmit buffer interrupt to fill it again with remaining data */
      while((XMC_USIC_CH_TXFIFO_GetEvent(XMC_UART0_CH0) & XMC_USIC_CH_TXFIFO_EVENT_STANDARD) == 0) {}
      XMC_USIC_CH_TXFIFO_ClearEvent(XMC_UART0_CH0, 256);
    }
}

extern "C" void CCU40_0_IRQHandler(void) {
  // Delete interrupt state
  XMC_CCU4_SLICE_ClearEvent(CCU4_SLICE_Pointer, XMC_CCU4_SLICE_IRQ_ID_PERIOD_MATCH);

  XMC_GPIO_ToggleOutput(XMC_GPIO_PORT5, 8U);

  uart_write("CCU0_0_IRQHandler\n");
}

void setup(void) {
    // LED-Pin initialization
    XMC_GPIO_Init(XMC_GPIO_PORT5, 8U, &Intr_pin);

    // UART inialization
    uart_init(115200);

    // CCU4-Modul initiazation
    XMC_CCU4_Init(CCU4_Module_Pointer, XMC_CCU4_SLICE_MCMS_ACTION_TRANSFER_PR_CR);
    XMC_CCU4_StartPrescaler(CCU4_Module_Pointer);

    // CCU4-Slice for Timer mode
    XMC_CCU4_SLICE_CompareInit(CCU4_SLICE_Pointer, &CCU4_Slice_Config);

    // Timer-Slice  (z. B. 1 Hz intterupt rate)
    //XMC_CCU4_SLICE_SetPrescaler(CCU4_SLICE_Pointer, XMC_CCU4_SLICE_PRESCALER_32768);  // Prescaler for 10 kHz frequency
    XMC_CCU4_SLICE_SetTimerPeriodMatch(CCU4_SLICE_Pointer, 8000); 
    XMC_CCU4_EnableShadowTransfer(CCU4_Module_Pointer, XMC_CCU4_SHADOW_TRANSFER_SLICE_0);
 
    // Tik for CCU4 relessing
    XMC_CCU4_EnableClock(CCU4_Module_Pointer, CCU4_SLICE_Pointer);

    // Interrupt Period-Match activation
    XMC_CCU4_SLICE_EnableEvent(CCU4_SLICE_Pointer, XMC_CCU4_SLICE_IRQ_ID_PERIOD_MATCH);
    XMC_CCU4_SLICE_SetInterruptNode(CCU4_SLICE_Pointer, XMC_CCU4_SLICE_IRQ_ID_PERIOD_MATCH, XMC_CCU4_SLICE_SR_ID_0);

    // NVIC CCU40_0_IRQHandler acitvation
    NVIC_SetPriority(CCU40_0_IRQn, 63);
    NVIC_EnableIRQ(CCU40_0_IRQn);

    // Timer starten
    XMC_CCU4_SLICE_StartTimer(CCU4_SLICE_Pointer);

    uart_write("setup finished\n");
}

void loop(void) {
  // TODO let sleep the MCU
  XMC_Delay(2000);
  uart_write("loop\n");
}
 